[package]
name = "pipes"
version = "0.1"
lean_version = "master"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/cipher1024/mathlib", rev = "17dfb6ee096cfc65884f8b2a6a7af8af3211120a"}
